const SIGNIN = {
    SIGNIN_LOAD: 'SIGNIN_LOAD',
    SIGNIN_LOAD_SUCCESS: 'SIGNIN_LOAD_SUCCESS',
    SIGNIN_LOAD_FAIL: 'SIGNIN_LOAD_FAIL'
}

const SIGNUP = {
    SIGNUP_LOAD: 'SIGNUP_LOAD',
    SIGNUP_LOAD_SUCCESS: 'SIGNUP_LOAD_SUCCESS',
    SIGNUP_LOAD_FAIL: 'SIGNUP_LOAD_FAIL'
}

const BOOKING = {
    BOOKING_LOAD: 'BOOKING_LOAD',
    BOOKING_LOAD_SUCCESS: 'BOOKING_LOAD_SUCCESS',
    BOOKING_LOAD_FAIL:'BOOKING_LOAD_SUCCESS'
}

export { SIGNIN,SIGNUP,BOOKING }